/**
 * QRScanner.tsx
 * -------------------------------------------------
 * Real camera-based QR code scanner for the Vendedor screen.
 *
 * Replaces the simulated barcode scanner with a live camera feed.
 * Uses expo-camera (bundled with Expo SDK 50+) which is the
 * recommended replacement for the deprecated expo-barcode-scanner.
 *
 * INSTALL:
 *   npx expo install expo-camera
 *
 * Also update app.json plugins array:
 *   "plugins": ["expo-camera", "expo-sharing"]
 *
 * USAGE:
 *   <QRScanner onScanned={(cedula) => handleLookup(cedula)} onClose={() => setScanning(false)} />
 * -------------------------------------------------
 */

import React, { useState, useEffect, useRef } from 'react';
import {
  View,
  Text,
  StyleSheet,
  TouchableOpacity,
  Platform,
  Alert,
} from 'react-native';
import { CameraView, useCameraPermissions } from 'expo-camera';

interface Props {
  onScanned: (data: string) => void;
  onClose:   () => void;
}

export default function QRScanner({ onScanned, onClose }: Props) {
  const [permission, requestPermission] = useCameraPermissions();
  const [scanned, setScanned]           = useState(false);
  const cooldown                        = useRef<ReturnType<typeof setTimeout> | null>(null);

  useEffect(() => {
    // Auto-request permission on mount
    if (permission && !permission.granted) {
      requestPermission();
    }
    return () => {
      if (cooldown.current) clearTimeout(cooldown.current);
    };
  }, []);

  // Web fallback — camera scanning doesn't work in a browser
  if (Platform.OS === 'web') {
    return (
      <View style={styles.webFallback}>
        <Text style={styles.webTitle}>Ingreso manual (Web)</Text>
        <Text style={styles.webSub}>
          El escáner QR requiere la app nativa (iOS / Android).{'\n'}
          Por favor ingresa la cédula del cliente manualmente.
        </Text>
        <TouchableOpacity style={styles.closeBtn} onPress={onClose}>
          <Text style={styles.closeTxt}>Cerrar</Text>
        </TouchableOpacity>
      </View>
    );
  }

  if (!permission) {
    return (
      <View style={styles.center}>
        <Text style={styles.msg}>Verificando permisos…</Text>
      </View>
    );
  }

  if (!permission.granted) {
    return (
      <View style={styles.center}>
        <Text style={styles.msg}>Se necesita acceso a la cámara para escanear QR.</Text>
        <TouchableOpacity style={styles.permBtn} onPress={requestPermission}>
          <Text style={styles.permTxt}>Conceder permiso</Text>
        </TouchableOpacity>
        <TouchableOpacity onPress={onClose}>
          <Text style={[styles.permTxt, { marginTop: 12, opacity: 0.6 }]}>Cancelar</Text>
        </TouchableOpacity>
      </View>
    );
  }

  const handleBarCodeScanned = ({ type, data }: { type: string; data: string }) => {
    if (scanned) return;
    setScanned(true);

    // The QR code encodes a JSON payload: { cedula, nombre, timestamp }
    // generated by the Comprador's PasaporteScreen QR.
    let cedula = data;
    try {
      const parsed = JSON.parse(data);
      if (parsed.cedula) cedula = parsed.cedula;
    } catch {
      // data is a raw cédula string — accept as-is
    }

    onScanned(cedula);

    // Allow re-scanning after 3 seconds
    cooldown.current = setTimeout(() => setScanned(false), 3000);
  };

  return (
    <View style={styles.container}>
      <CameraView
        style={StyleSheet.absoluteFillObject}
        facing="back"
        barcodeScannerSettings={{ barcodeTypes: ['qr'] }}
        onBarcodeScanned={scanned ? undefined : handleBarCodeScanned}
      />

      {/* Viewfinder overlay */}
      <View style={styles.overlay}>
        <View style={styles.dimTop} />
        <View style={styles.middle}>
          <View style={styles.dimSide} />
          <View style={styles.frame}>
            <View style={[styles.corner, styles.tl]} />
            <View style={[styles.corner, styles.tr]} />
            <View style={[styles.corner, styles.bl]} />
            <View style={[styles.corner, styles.br]} />
          </View>
          <View style={styles.dimSide} />
        </View>
        <View style={styles.dimBottom}>
          <Text style={styles.hint}>
            {scanned ? '✓ QR leído — procesando…' : 'Apunta la cámara al código QR del cliente'}
          </Text>
          <TouchableOpacity style={styles.closeBtn} onPress={onClose}>
            <Text style={styles.closeTxt}>✕ Cancelar</Text>
          </TouchableOpacity>
        </View>
      </View>
    </View>
  );
}

const FRAME = 240;
const CORNER = 24;
const BORDER = 3;
const C_COLOR = '#C8860A';

const styles = StyleSheet.create({
  container:   { flex: 1, backgroundColor: '#000' },
  center:      { flex: 1, justifyContent: 'center', alignItems: 'center', backgroundColor: '#1A0F00', padding: 24 },
  msg:         { color: '#F5EDD8', textAlign: 'center', fontSize: 16, marginBottom: 20 },
  permBtn:     { backgroundColor: '#C8860A', paddingHorizontal: 28, paddingVertical: 12, borderRadius: 8 },
  permTxt:     { color: '#1A0F00', fontWeight: '700', fontSize: 15 },

  // Web fallback
  webFallback: { flex: 1, justifyContent: 'center', alignItems: 'center', backgroundColor: '#1A0F00', padding: 32 },
  webTitle:    { color: '#C8860A', fontSize: 20, fontWeight: '700', marginBottom: 12 },
  webSub:      { color: '#A89070', fontSize: 14, textAlign: 'center', lineHeight: 22 },

  // Overlay
  overlay:     { ...StyleSheet.absoluteFillObject, flexDirection: 'column' },
  dimTop:      { flex: 1, backgroundColor: 'rgba(0,0,0,0.65)' },
  middle:      { height: FRAME, flexDirection: 'row' },
  dimSide:     { flex: 1, backgroundColor: 'rgba(0,0,0,0.65)' },
  frame:       { width: FRAME, height: FRAME },
  dimBottom:   { flex: 1.2, backgroundColor: 'rgba(0,0,0,0.65)', alignItems: 'center', justifyContent: 'center', gap: 20 },
  hint:        { color: '#F5EDD8', fontSize: 14, textAlign: 'center', paddingHorizontal: 32 },

  // Corner markers
  corner:      { position: 'absolute', width: CORNER, height: CORNER, borderColor: C_COLOR },
  tl:          { top: 0,        left: 0,        borderTopWidth: BORDER, borderLeftWidth:  BORDER },
  tr:          { top: 0,        right: 0,       borderTopWidth: BORDER, borderRightWidth: BORDER },
  bl:          { bottom: 0,     left: 0,        borderBottomWidth: BORDER, borderLeftWidth:  BORDER },
  br:          { bottom: 0,     right: 0,       borderBottomWidth: BORDER, borderRightWidth: BORDER },

  closeBtn:    { backgroundColor: '#2C1A00', borderWidth: 1, borderColor: '#C8860A', paddingHorizontal: 28, paddingVertical: 10, borderRadius: 8 },
  closeTxt:    { color: '#C8860A', fontWeight: '700', fontSize: 15 },
});
